# Target time in milliseconds since Unix Epoch (https://currentmillis.com/)
target: 1735339500000
triggers:
  100000000:
    - "say This will be called once and for sure, you can initialize scoreboards and stuff here"
  -100000000:
    - "say &3%countdown% seconds left!" # & character is used for color, and %countdown% for the countdown in seconds
  60:
    - "say &4Last %countdown% seconds!"
  30:
    - "say &4&bLAST %countdown% SECONDS!"
  -10:
    - "say &6%countdown%!"
    - "give @a minecraft:diamond"
  0:
    - "say &7OLEY!"
