name: FinalTick
version: '1.0.0'
main: com.karahanbuhan.finaltick.FinalTickPlugin
api-version: '1.21'
authors: [ Karahan ]
description: Countdown to a time specified in config file with custom command triggers.
